### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by sudoharun** [Xtr126/wayland-getevent#1]
As the title suggests, I have not gotten this to work a single time with Waydroid. I have tried on Hyprland (what I use mainly), and even installed KDE Plasma just for this, in focus, out of focus, and still nothing. When XtMapper client is in focus, my cursor disappears and nothing happens at all. When it is out of focus, nothing.

Any possible reason for this? Is the issue wayland-side? I have seen a YT video that demonstrates this tool, so has this stopped working recently for others too and not just for me?

**Comment by Xtr126** [comment]
> As the title suggests, I have not gotten this to work a single time with Waydroid. I have tried on Hyprland (what I use mainly), and even installed KDE Plasma just for this, in focus, out of focus, and still nothing. When XtMapper client is in focus, my cursor disappears and nothing happens at all. When it is out of focus, nothing.
> 
> Any possible reason for this? Is the issue wayland-side? I have seen a YT video that demonstrates this tool, so has this stopped working recently for others too and not just for me?

Run the client binary in the host by executing `./client` and check the output, if there is no useful output then it might be a wayland related issue, but it is very unlikely.

Also try running it from the host with `./path/to/client | sudo waydroid shell -- sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client` 
` instead of pushing the client to the container

**Comment by sudoharun** [comment]
I only managed to get it working once on Hyprland, however the keybindings wouldn't persist and kept resetting after I saved the changes. Here is a video (sorry for quality in advance) showcasing what I'm doing and what is going on (please note that `./client` is a floating window overlaying everything, so when the windows are dimmed, that means that `./client` is the active window)

https://github.com/Xtr126/wayland-getevent/assets/123123333/4dd8294c-ad4b-4c7a-a384-15ec41c5f8d2


Edit: I can confirm that the exact same thing is taking place on Plasma Wayland

**Comment by Xtr126** [comment]
> I only managed to get it working once on Hyprland, however the keybindings wouldn't persist and kept resetting after I saved the changes. Here is a video (sorry for quality in advance) showcasing what I'm doing and what is going on (please note that `./client` is a floating window overlaying everything, so when the windows are dimmed, that means that `./client` is the active window)
> 
>  e353e8e6-9a9f-4a0e-a25f-9f3d38cf7f2b.mp4 
> Edit: I can confirm that the exact same thing is taking place on Plasma Wayland

Did you click on start button after seeing the text "using wayland client" ? 
If not then try doing so (remove client from focus to click on start button and bring it back), I think that is most likely the issue. When running XtMapper on systems other than waydroid it does show a notification to the user, I'll try to find a solution for it.

**Comment by Xtr126** [comment]
And about the keybindings not persisting issue, disabling auto-profiling from settings should help.

**Comment by sudoharun** [comment]
Even after following your instructions, the issue still persists. I think even yesterday I tried that, and it worked the first time then never worked again. On both Hyprland and KDE Plasma. Does this mean that the issue is with XtMapper itself and the `--wayland-client` launch option? Anyway here is a video of my following your instructions for verification.

https://github.com/Xtr126/wayland-getevent/assets/123123333/25c7ae48-1ee6-4c6f-b9d5-9409f3efc342

**Comment by Xtr126** [comment]
> Even after following your instructions, the issue still persists. I think even yesterday I tried that, and it worked the first time then never worked again. On both Hyprland and KDE Plasma. Does this mean that the issue is with XtMapper itself and the `--wayland-client` launch option? Anyway here is a video of my following your instructions for verification.
> 
>  2023-12-14.17-12-38.mp4

Appreciate that you took the time to send a detailed video, I saw that you have keymapping disabled as it says: 
![image](https://github.com/Xtr126/wayland-getevent/assets/80520774/9fe6e2b2-7c51-41e0-8d72-e7c55f15aaee)
Try enabling it from the switch or disabling auto-profiling.

**Comment by sudoharun** [comment]
> > Even after following your instructions, the issue still persists. I think even yesterday I tried that, and it worked the first time then never worked again. On both Hyprland and KDE Plasma. Does this mean that the issue is with XtMapper itself and the `--wayland-client` launch option? Anyway here is a video of my following your instructions for verification.
> > 2023-12-14.17-12-38.mp4
> 
> Appreciate that you took the time to send a detailed video, I saw that you have keymapping disabled as it says: ![image](https://private-user-images.githubusercontent.com/80520774/290756219-9fe6e2b2-7c51-41e0-8d72-e7c55f15aaee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTYwNTcsIm5iZiI6MTcwMjY1NTc1NywicGF0aCI6Ii84MDUyMDc3NC8yOTA3NTYyMTktOWZlNmUyYjItN2M1MS00MWUwLThkNzItZTdjNTVmMTVhYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE1NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViN2U3ZjQwNjgzODdmZjA3NjcxNmVhZDdhZGMyNGJlY2FiNTNjODNiY2UwMjE2MzdmYTY2NjZjZGE1N2RhYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivAl6VjiAC30qAApa0e9kJy3B15fKlU2xaGklCPnItY) Try enabling it from the switch or disabling auto-profiling.

Ah OK so that was the issue! You have to enable keybindings for every single application otherwise it won't work. It works perfectly well now. Thank you for your time and help, and I hope this thread is able to help someone else :)
