### ISSUE TITLE
Window needs to be focused to get input on hyprland

### ISSUE THREAD

**Issue by sassywoocoo** [Xtr126/wayland-getevent#10]
I use arch linux with the hyprland window manager. wayland-getevents works as intended and it can capture keystrokes and forward them to xtmapper. but only when the wayland-getevents is focused.
wayland apparently does not allow apps to read keystrokes from other applications.
so do you guys have a fix for this or should i just cope

**Comment by Xtr126** [comment]
As mentioned in the README using cage is being tried as a possible solution, you can test it. Hopefully it becomes more convenient to use.

**Comment by sassywoocoo** [comment]
thanks Xtr126. that was the kind of answer I was looking for.

**Comment by Xtr126** [comment]
New [cage_xtmapper.sh](https://github.com/Xtr126/cage/blob/master/cage_xtmapper.sh) script should make it easier.
