### ISSUE TITLE
Building in fedora

### ISSUE THREAD

**Issue by androguy06** [Xtr126/wayland-getevent#13]
Please provide dependency list for building in fedora

**Comment by Xtr126** [comment]
Let me see if it's easy enough to build on fedora

**Comment by Xtr126** [comment]
These should be the dependencies:
https://src.fedoraproject.org/rpms/cage/blob/205660f87689643e1f9098f4a816dfc80c43254f/f/cage.spec#_15

https://src.fedoraproject.org/rpms/wlroots/blob/ebd7df88f6dcfbfebe584c68ab0741e82d1de74a/f/wlroots.spec#_49
