### ISSUE TITLE
[feature request] Direct touchpad mode

### ISSUE THREAD

**Issue by mineland-2048** [Xtr126/wayland-getevent#14]
Wondering if the touchpad option in xtmapper could work here while using waydroid. It would be insanely convinient for certain games without having to go the full bliss os route

**Comment by Xtr126** [comment]
> Wondering if the touchpad option in xtmapper could work here while using waydroid. It would be insanely convinient for certain games without having to go the full bliss os route

There is no /dev/uinput or root access in waydroid by default so I cannot add support for it. 
You could do it with a simple /run/udev hack on the host, run `grep -rn TOUCHPAD /run/udev/` to find the flag and flip it to 0 to make the touchpad behave as a direct touchscreen. Restart your DE to make effect.

**Comment by mineland-2048** [comment]
> run grep -rn TOUCHPAD /run/udev/ to find the flag and flip it to 0 to make the touchpad behave as a direct touchscreen

i did that to see what would happen (via editing the files that the command showed as text files) , but it just disabled the touchpad from working entirely after logging out and back in to reload the DE (kde plasma 6.2.0)
not sure if i did something wrong? or if thats something to do with this touchpad? but it makes sense based on what its doing
![image](https://github.com/user-attachments/assets/d474b694-5e5e-40d4-9ecb-7fa341efcb2e)
the ones with 0 were 1 before changing them

(edit: if this is beyond the scope of the project then i should probably stop the thread, but everywhere i find is people asking how to fix a touchpad behaving like a touchscreen, and not the other way around, so this is a bit of a lead)

**Comment by Xtr126** [comment]
> > run grep -rn TOUCHPAD /run/udev/ to find the flag and flip it to 0 to make the touchpad behave as a direct touchscreen
> 
> i did that to see what would happen (via editing the files that the command showed as text files) , but it just disabled the touchpad from working entirely after logging out and back in to reload the DE (kde plasma 6.2.0) not sure if i did something wrong? or if thats something to do with this touchpad? but it makes sense based on what its doing ![image](https://private-user-images.githubusercontent.com/159833296/376900364-d474b694-5e5e-40d4-9ecb-7fa341efcb2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTg3MjgsIm5iZiI6MTcyOTA1ODQyOCwicGF0aCI6Ii8xNTk4MzMyOTYvMzc2OTAwMzY0LWQ0NzRiNjk0LTVlNWUtNDBkNC05ZWNiLTdmYTM0MWVmY2IyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwNjAwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTYzOWJkYWQ5NTBmYmExNWM3NjMxZWU3YWZkN2M2ZjVjMjU5YmE5ZGUyMGY5MTNiYTk0NTA3ZDQ2MzQ1N2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vhi9H7eG61zKLGE_BLB7F3f8yahSp0DAt4VEqH4O7iM) the ones with 0 were 1 before changing them
> 
> (edit: if this is beyond the scope of the project then i should probably stop the thread, but everywhere i find is people asking how to fix a touchpad behaving like a touchscreen, and not the other way around, so this is a bit of a lead)

Sorry I used that hack long ago so I forgot, we actually have to change `ID_INPUT_TOUCHPAD` to `ID_INPUT_TOUCHSCREEN`. So the following command would do that easily:
```bash
 sudo find /run/udev -type f -exec sed -i 's/ID_INPUT_TOUCHPAD/ID_INPUT_TOUCHSCREEN/g' {} \;
```
To revert:
```bash
 sudo find /run/udev -type f -exec sed -i 's/ID_INPUT_TOUCHSCREEN/ID_INPUT_TOUCHPAD/g' {} \;
```
Works fine on plasma 6.1.5 and Arch Linux. 
Also recommend enabling "Touch points" from System Settings > Window Management > Desktop effects to visualize touches. 
I have not tested, but adding `/dev/uinput` to `/var/lib/waydroid/lxc/waydroid/config_nodes` should enable XtMapper to do that as well.
