### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by ipation** [Xtr126/wayland-getevent#3]
Hi, sorry to use "issue" in order to ask a question, but I didn't know how to contact you.
I've tried your work on Ubuntu 22.04.3 (wayland), latest Waydroid, and the Android game ClashOfClans, and it works perfectly!
However, the only thing not working for me with waydroid (alone) is the zoom-in zoom-out (that I can achieve thanks to your work with ctrl+mouse move). 
So my question is, how can I accomplish your zoom-in/zoom-out programmatically ? Without using physical keyboard or mouse, just on-demand. I know my way a bit around programming.
Thank you.

**Comment by Xtr126** [comment]
You can have a look at InputShellCommand in AOSP for simulating touch events. https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/input/InputShellCommand.java 
XtMapper uses the same APIs for it. MousePinchZoom/MouseWheelZoom java classes in XtMapper source are responsible for the zoom functionality. It is a simple implementation using two pointers (fingers) and moving them away from a fixed point.
There are other ways to do it, to use the Android InputManager APIs a jar file or APK should be compiled and run with app_process.

**Comment by nouatzi** [comment]
Thank you very much. That's a good pointer for me.

**Comment by ipation** [comment]
Me too. Thanks.
