### ISSUE TITLE
I got a problem that the window is 'hiding' the cursor now

### ISSUE THREAD

**Issue by InternetRebelAKAQuachHungPhong** [Xtr126/wayland-getevent#4]
If you don't mind this, so recently, I tried to use this application on Ubuntu, with the new usage with terminal lines, the issue of the window not showing my cursor like it used to occured, in which I can still click the Waydroid screen normally with it. The latest binary build doesn't seem to get better with this, even though I opened the same directory of it in terminal and entered the command line as in usage:
`./client | sudo waydroid shell -- sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client`

Now I wonder what if I try entering two other terminal lines from, like, months ago. I think I lost them and I can't remember them of course. Well, I'm not sure much to say, or describe, can you recall any of that? It's a series of three command lines to enter in Waydroid shell, in which the last one looked similar to this:
`sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client`

**Comment by Xtr126** [comment]
> If you don't mind this, so recently, I tried to use this application on Ubuntu, with the new usage with terminal lines, the issue of the window not showing my cursor like it used to occured, in which I can still click the Waydroid screen normally with it. The latest binary build doesn't seem to get better with this, even though I opened the same directory of it in terminal and entered the command line as in usage: `./client | sudo waydroid shell -- sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client`
> 
> Now I wonder what if I try entering two other terminal lines from, like, months ago. I think I lost them and I can't remember them of course. Well, I'm not sure much to say, or describe, can you recall any of that? It's a series of three command lines to enter in Waydroid shell, in which the last one looked similar to this: `sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client`

Using libwayland-cursor to set a cursor for the window should fix it, but it segfaults on my system. 
This was not an issue on kwin_wayland however. 
So use a different wayland compositor.

**Comment by InternetRebelAKAQuachHungPhong** [comment]
I'll try and see

Wait, how do I know which compositor am I using and how to change it? Is it the same to window manager?

**Comment by Xtr126** [comment]
> I'll try and see
> 
> Wait, how do I know which compositor am I using and how to change it? Is it the same to window manager?

On ubuntu if you use gnome then mutter is the wayland compositor.
Maybe a different mutter version doesn’t have the issue.
But someone on youtube seems to have it working fine on mutter https://youtu.be/Aq17lQi35wc?si=9Qt0zCA4wfQ3g_As
The easiest way to try a different wayland compositor is by changing your desktop environment. I only tested on plasma myself.

**Comment by InternetRebelAKAQuachHungPhong** [comment]
Everyone, anyway, here are three things I concluded yesterday:

1. It seems for me that you would have to open the binary's directory in terminal and then open it _and_ the Waydroid shell command to activate XtMapper **in the same terminal window**, in order to get the binary-window to actually work in inputting touches/clicks in the Waydroid window when XtMapper is started(for now, gonna experiment more)
2. It seems this is a good alternative to scrcpy, which streams the Waydroid display - especially on the same machine/system, and also does 'normal' touch inputs (unlike how the Linux cursor and the Waydroid system(as well as several apps and games) acts as if this cursor was the Android system's;which probably is why it doesn't work in several games); like, I've been trying and following this for months already.
3. I discovered a workaround to this issue: open any window(like a terminal) _and_ always make sure when you click the minimize button it would switch to the XtMapper window - the cursor would always/likely be shown when in the XtMapper invisible window. Maybe try to not switch to especially the Waydroid window.

Guess it's enough to talk about this now.

**Comment by InternetRebelAKAQuachHungPhong** [comment]
So, by the way, what's with Auto Profiling in XtMapper with this?

(Should this be opened as a new issue?)

**Comment by Xtr126** [comment]
Open a new issue if there is a bug with auto profiling feature.

**Comment by Xtr126** [comment]
`waydroid prop set persist.waydroid.cursor_on_subsurface true` should fix it.
