### ISSUE TITLE
/sdcard/Android/data/xtr.keymapper/files/xtMapper.sh: No such file or directory

### ISSUE THREAD

**Issue by mesflit** [Xtr126/wayland-getevent#5]
./client | sudo waydroid shell -- sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh --wayland-client
sh: /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh: No such file or directory

version 2.1.4 xtmapper

**Comment by mistrmochov** [comment]
Same issue here, I tried to go through almost all versions, in version 2.1.0, I was able to launch the client, however It didn't work at all together with xtrmapper :(

**Comment by Xtr126** [comment]
This is a waydroid problem, this workaround may work: https://github.com/casualsnek/waydroid_script?tab=readme-ov-file#granting-full-permission-for-apps-data-hack
Restart the app for it to write the script to storage.

**Comment by mesflit** [comment]
> This is a waydroid problem, this workaround may work: https://github.com/casualsnek/waydroid_script?tab=readme-ov-file#granting-full-permission-for-apps-data-hack Restart the app for it to write the script to storage.

How to use it " sudo venv/bin/python3 main.py hack nodataperm " for xtMapper

**Comment by mesflit** [comment]
But there is no such file error in version 2.1.0. But xtmapper is not working

**Comment by Xtr126** [comment]
> But there is no such file error in version 2.1.0. But xtmapper is not working

I can't reproduce this error with 2.1.4 on my end.


> > This is a waydroid problem, this workaround may work: https://github.com/casualsnek/waydroid_script?tab=readme-ov-file#granting-full-permission-for-apps-data-hack Restart the app for it to write the script to storage.
> 
> How to use it " sudo venv/bin/python3 main.py hack nodataperm " for xtMapper

Below that, commands to run in `sudo waydroid shell` are listed, try running those chmod commands.

**Comment by Xtr126** [comment]
If your waydroid container is rooted and XtMapper is granted root access, then it won't write the script to storage as it will assume that you use the root activation method.

**Comment by null2264** [comment]
> If your waydroid container is rooted and XtMapper is granted root access, then it won't write the script to storage as it will assume that you use the root activation method.

Ah, so that's what happened, I ended up creating this shell script following XtMapper documentation since I was so confused why it wouldn't write the script:

```sh
doas waydroid shell -- sh -c 'echo "/system/bin/app_process -Djava.library.path=$(echo /data/app/*/xtr.keymapper*/lib/x86_64) -Djava.class.path=$(echo /data/app/*/xtr.keymapper*/base.apk) / xtr.keymapper.server.RemoteServiceShell --wayland-client" > /tmp/xtmapper.sh'

xtmapper-client | doas waydroid shell -- sh /tmp/xtmapper.sh
```

**Comment by mesflit** [comment]
> If your waydroid container is rooted and XtMapper is granted root access, then it won't write the script to storage as it will assume that you use the root activation method.

It worked, but this time the waydroid shell command did not work and I later gave root permission to the application. So after writing the files

**Comment by Xtr126** [comment]
> > If your waydroid container is rooted and XtMapper is granted root access, then it won't write the script to storage as it will assume that you use the root activation method.
> 
> It worked, but this time the waydroid shell command did not work and I later gave root permission to the application. So after writing the files

It doesn't need root permission however. I'll update the documentation to make it more clear, thanks for reporting the issue.
