### ISSUE TITLE
bulding cage in fedora

### ISSUE THREAD

**Issue by DieALot36T9** [Xtr126/wayland-getevent#7]
diealotto@fedora:~/cage$ meson setup build --buildtype=release
The Meson build system
Version: 1.4.0
Source dir: /home/diealotto/cage
Build dir: /home/diealotto/cage/build
Build type: native build
Project name: cage
Project version: 0.1.5
C compiler for the host machine: cc (gcc 14.0.1 "cc (GCC) 14.0.1 20240411 (Red Hat 14.0.1-0)")
C linker for the host machine: cc ld.bfd 2.41-34
Host machine cpu family: x86_64
Host machine cpu: x86_64

Executing subproject wlroots 

wlroots| Project name: wlroots
wlroots| Project version: 0.17.2
wlroots| C compiler for the host machine: cc (gcc 14.0.1 "cc (GCC) 14.0.1 20240411 (Red Hat 14.0.1-0)")
wlroots| C linker for the host machine: cc ld.bfd 2.41-34
wlroots| Compiler for C supports arguments -Wundef: YES
wlroots| Compiler for C supports arguments -Wlogical-op: YES
wlroots| Compiler for C supports arguments -Wmissing-include-dirs: YES
wlroots| Compiler for C supports arguments -Wold-style-definition: YES
wlroots| Compiler for C supports arguments -Wpointer-arith: YES
wlroots| Compiler for C supports arguments -Winit-self: YES
wlroots| Compiler for C supports arguments -Wstrict-prototypes: YES
wlroots| Compiler for C supports arguments -Wimplicit-fallthrough=2: YES
wlroots| Compiler for C supports arguments -Wendif-labels: YES
wlroots| Compiler for C supports arguments -Wstrict-aliasing=2: YES
wlroots| Compiler for C supports arguments -Woverflow: YES
wlroots| Compiler for C supports arguments -Wmissing-prototypes: YES
wlroots| Compiler for C supports arguments -Walloca: YES
wlroots| Compiler for C supports arguments -Wno-missing-braces: YES
wlroots| Compiler for C supports arguments -Wno-missing-field-initializers: YES
wlroots| Compiler for C supports arguments -Wno-unused-parameter: YES
wlroots| Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES
wlroots| Found pkg-config: YES (/usr/bin/pkg-config) 2.1.0
wlroots| Run-time dependency wayland-server found: YES 1.22.0
wlroots| Run-time dependency libdrm found: YES 2.4.120
wlroots| Run-time dependency xkbcommon found: YES 1.6.0
wlroots| Run-time dependency pixman-1 found: YES 0.43.4
wlroots| Library m found: YES
wlroots| Library rt found: YES
wlroots| Run-time dependency wayland-protocols found: YES 1.36
wlroots| Build-time dependency wayland-scanner found: YES 1.22.0
wlroots| Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
wlroots| Has header "linux/dma-buf.h" : YES
wlroots| Run-time dependency egl found: YES 1.5
wlroots| Found CMake: /usr/bin/cmake (3.28.2)
wlroots| Run-time dependency gbm found: NO (tried pkgconfig and cmake)
wlroots| Run-time dependency glesv2 found: YES 3.2
wlroots| Run-time dependency vulkan found: NO (tried pkgconfig and system)
wlroots| Message: Required for vulkan renderer support.
wlroots| Dependency pixman-1 found: YES 0.43.4 (cached)
wlroots| Run-time dependency gbm found: NO (tried pkgconfig and cmake)
wlroots| Run-time dependency libudev found: NO (tried pkgconfig and cmake)
wlroots| Message: Required for session support.
wlroots| Run-time dependency libseat found: NO (tried pkgconfig and cmake)
wlroots| Looking for a fallback subproject for the dependency libseat
wlroots| Neither a subproject directory nor a seatd.wrap file was found.
wlroots| Subproject  seatd is buildable: NO (disabling)
wlroots| Dependency libseat from subproject seatd found: NO (subproject failed to configure)
wlroots| Message: Required for session support.
wlroots| Run-time dependency wayland-client found: YES 1.22.0
wlroots| Dependency xwayland skipped: feature xwayland disabled
wlroots| Configuring config.h using configuration
wlroots| Configuring version.h using configuration
wlroots| Configuring config.h using configuration
wlroots| Build targets in project: 127
wlroots| Subproject wlroots finished.

Dependency wayland-protocols found: YES 1.36 (cached)
Dependency wayland-server found: YES 1.22.0 (cached)
Dependency xkbcommon found: YES 1.6.0 (cached)
Library m found: YES
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Program git found: YES (/usr/bin/git)
Dependency scdoc skipped: feature man-pages disabled
Configuring config.h using configuration
Message: 
Cage 0.1.5-b1d3a81 (branch 'master')

    xwayland: false

Build targets in project: 128

wlroots 0.17.2

    drm-backend     : NO
    x11-backend     : NO
    libinput-backend: NO
    xwayland        : NO
    gles2-renderer  : NO
    vulkan-renderer : NO
    gbm-allocator   : NO
    session         : NO
    xcb-errors      : NO
    egl             : NO

cage 0.1.5

  Subprojects
    seatd    : NO
               Neither a subproject directory nor a seatd.wrap file was found.
    wlroots  : YES

  User defined options
    buildtype: release

Found ninja-1.11.1 at /usr/bin/ninja
.
.
.
this happens while building in fedora. any suggestions?

**Comment by DieALot36T9** [comment]
diealotto@fedora:~/cage$ ninja -C build
ninja: Entering directory `build'
[1/1] Linking target cage
FAILED: cage 
cc  -o cage cage.p/cage.c.o cage.p/idle_inhibit_v1.c.o cage.p/output.c.o cage.p/seat.c.o cage.p/view.c.o cage.p/xdg_shell.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 '-Wl,-rpath,$ORIGIN/subprojects/wlroots' -Wl,-rpath-link,/home/diealotto/cage/build/subprojects/wlroots -Wl,--start-group subprojects/wlroots/libwlroots.so.12 /usr/lib64/libwayland-server.so /usr/lib64/libdrm.so /usr/lib64/libxkbcommon.so /usr/lib64/libpixman-1.so -lm -lrt /usr/lib64/libwayland-client.so -Wl,--end-group
/usr/bin/ld: cage.p/seat.c.o: in function `handle_keyboard_group_key':
seat.c:(.text+0x83d): undefined reference to `wlr_session_change_vt'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
diealotto@fedora:~/cage$ 



also this

**Comment by Xtr126** [comment]
It looks like you are building this on a different system, dependencies are missing for GPU acceleration and session support as in the logs which causes the undefined reference error. Try installing wlroots and cage packages on host which might install the missing dependencies.

**Comment by DieALot36T9** [comment]
> It looks like you are building this on a different system, dependencies are missing for GPU acceleration and session support as in the logs which causes the undefined reference error. Try installing wlroots and cage packages on host which might install the missing dependencies.



I'm using a wayland system(fedora 40 gnome workstation). Gpu drivers and gdm are already present. but somehow  not being detected(?)

**Comment by Xtr126** [comment]
> > It looks like you are building this on a different system, dependencies are missing for GPU acceleration and session support as in the logs which causes the undefined reference error. Try installing wlroots and cage packages on host which might install the missing dependencies.
> 
> I'm using a wayland system(fedora 40 gnome workstation). Gpu drivers and gdm are already present. but somehow not being detected(?)

It’s worth checking if you can build wlroots main project (0.17.2) with session enabled: https://gitlab.freedesktop.org/wlroots/wlroots. If not it might be a meson related issue on the fedora system and not related to this repository.

**Comment by DieALot36T9** [comment]
> > > It looks like you are building this on a different system, dependencies are missing for GPU acceleration and session support as in the logs which causes the undefined reference error. Try installing wlroots and cage packages on host which might install the missing dependencies.
> > 
> > 
> > I'm using a wayland system(fedora 40 gnome workstation). Gpu drivers and gdm are already present. but somehow not being detected(?)
> 
> It’s worth checking if you can build wlroots main project (0.17.2) with session enabled: https://gitlab.freedesktop.org/wlroots/wlroots. If not it might be a meson related issue on the fedora system and not related to this repository.

 

seems like fedora is not a good match....should  I close this issue?

**Comment by Xtr126** [comment]
Thank you for testing, not sure what I can do for fedora so closing. cage is experimental for now, later I'll try to setup a CI build.

**Comment by llc0930** [comment]
@DieALot36T9, you need to install these packages:
`mesa-libgbm-devel` `systemd-devel` `libseat-devel`
